In [1]:
from Alpcca import ALPCCA   #ALPCCA is the class present in folder Alpcca.py
import pandas as pd
import numpy as np

In [2]:
x=pd.read_csv(r'mfeat-mor.csv',delim_whitespace=True,header=None)
y=pd.read_csv(r'mfeat-fou.csv',delim_whitespace=True,header=None)

In [3]:
print("Enter the k value (K is the number of neighbors to consider);")
k=int(input())

Enter the k value (K is the number of neighbors to consider);
5


In [4]:
alpcca=ALPCCA(x,y,k)
X_new,Y_new=alpcca.fit_transform()
print("Reduced X :")
print(X_new)
print("Reduced Y :")
print(Y_new)

Reduced X :
[[-1.85218780e+00 -9.22528485e-02 -4.26144687e-03  1.66203997e-03
   8.58032284e-07  6.73720243e-08]
 [-1.81843255e+00 -8.87476663e-02 -3.30514356e-03  1.60645507e-03
   2.80098796e-06  7.33782838e-09]
 [-1.80602319e+00 -9.20286331e-02 -4.07694117e-03  1.61608703e-03
   1.31806139e-06  2.67205300e-08]
 ...
 [-3.58780478e+00 -6.18893843e-02  4.14359222e-03 -2.43026876e-03
   9.58148663e-08 -2.91321445e-07]
 [-3.88119231e+00 -6.00778224e-02  3.76951470e-03 -2.16083699e-03
  -1.31664168e-06  6.15775060e-08]
 [-3.61688976e+00 -6.08916275e-02  4.30569485e-03 -2.40804463e-03
   3.79956835e-07 -3.48302834e-07]]
Reduced Y :
[[-1.42848054e+01 -5.21881027e-02  1.14551815e-02 ...  1.03737410e-04
  -8.79457261e-04  6.42785142e-05]
 [-1.28296365e+01 -7.02891320e-02  1.63442323e-02 ...  1.31758976e-03
  -2.32939044e-03  8.73098377e-04]
 [-1.26670950e+01 -6.71200054e-02  8.64142729e-03 ...  1.28839276e-03
  -2.52023977e-03  1.75671816e-03]
 ...
 [-1.74289165e+01 -6.19239791e-04  3.4110892

## Example 1

In [5]:
X = [[0., 0., 1.], [1.,0.,0.], [2.,2.,2.], [3.,5.,4.]]
Y = [[0.1, -0.2], [0.9, 1.1], [6.2, 5.9], [11.9, 12.3]]
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [6]:
alpcca=ALPCCA(X,Y,4)
X_new,Y_new=alpcca.fit_transform()
print("Reduced X :")
print(X_new)
print("Reduced Y :")
print(Y_new)

Reduced X :
[[-3.89568618e-01  2.13556612e-03 -4.17675651e-03]
 [-4.31846932e-01 -6.58903451e-03  4.99618852e-03]
 [-2.36052549e+00 -2.68020548e-03  1.58106910e-03]
 [-4.64805125e+00  4.34198921e-03 -1.86294779e-03]]
Reduced Y :
[[ 1.02884411e-02 -6.85580837e-06]
 [-2.08428353e-01  4.44121843e-06]
 [-1.26168393e+00 -7.67186522e-06]
 [-2.52290932e+00  7.53126077e-06]]


## Example 2 

In [7]:
X = [[0.3, 0.2, 1.5], [1.3,0.2,0.5], [2.3,2.2,2.5], [3.3,5.2,4.5]]
Y = [[0.1, -0.2], [0.9, 1.1], [6.2, 5.9], [11.9, 12.3]]
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [8]:
alpcca=ALPCCA(X,Y,4)
X_new,Y_new=alpcca.fit_transform()
print("Reduced X :")
print(X_new)
print("Reduced Y :")
print(Y_new)

Reduced X :
[[-6.88909943e-01 -1.06153608e-03 -3.30302871e-03]
 [-7.32477554e-01 -4.88602738e-03  3.80084631e-03]
 [-2.45463577e+00 -2.14592024e-03  1.32496153e-03]
 [-4.50810869e+00  4.44713467e-03 -1.46458793e-03]]
Reduced Y :
[[ 1.02884411e-02 -6.85741966e-06]
 [-2.08428353e-01  4.47386062e-06]
 [-1.26168393e+00 -7.47427153e-06]
 [-2.52290932e+00  7.92637635e-06]]
